version: '3.8'

services:

  beya_backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile
      container_name: beya_backend_container
      env_file:
        - .env.production
      volumes:
        - sqlite_data:/app/src/Database
      networks:
        - beya_network
      ports:
        - 3000:3000
  

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - beya_network
    depends_on:
      - beya_backend

volumes:
  sqlite_data:
    driver: local 

networks:
  beya_network:
    name: beya_backend_network